// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'error.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

Future<AccountSettings> getAccountSettings({required String pubkey}) =>
    RustLib.instance.api.crateApiAccountSettingsGetAccountSettings(pubkey: pubkey);

Future<AccountSettings> updateNotificationsEnabled({
  required String pubkey,
  required bool enabled,
}) => RustLib.instance.api.crateApiAccountSettingsUpdateNotificationsEnabled(
  pubkey: pubkey,
  enabled: enabled,
);

/// Per-account settings exposed to Flutter.
class AccountSettings {
  final bool notificationsEnabled;
  final DateTime createdAt;
  final DateTime updatedAt;

  const AccountSettings({
    required this.notificationsEnabled,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode => notificationsEnabled.hashCode ^ createdAt.hashCode ^ updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountSettings &&
          runtimeType == other.runtimeType &&
          notificationsEnabled == other.notificationsEnabled &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
