// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import '../lib.dart';
import 'accounts.dart';
import 'error.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `backend`, `clone`, `fmt`, `get_public_key`, `nip04_decrypt`, `nip04_encrypt`, `nip44_decrypt`, `nip44_encrypt`, `sign_event`

/// Login with an external signer (like Amber via NIP-55) and publish key package.
///
/// This function creates an account for the given public key and uses the provided
/// callbacks to sign the key package event, allowing the account to receive MLS
/// messages.
///
/// # Arguments
///
/// * `pubkey` - The user's public key (hex format) obtained from the external signer.
/// * `sign_event` - Callback to sign unsigned events. Takes unsigned event JSON, returns signed event JSON.
/// * `nip04_encrypt` - Callback for NIP-04 encryption. Takes (plaintext, recipient_pubkey), returns ciphertext.
/// * `nip04_decrypt` - Callback for NIP-04 decryption. Takes (ciphertext, sender_pubkey), returns plaintext.
/// * `nip44_encrypt` - Callback for NIP-44 encryption. Takes (plaintext, recipient_pubkey), returns ciphertext.
/// * `nip44_decrypt` - Callback for NIP-44 decryption. Takes (ciphertext, sender_pubkey), returns plaintext.
Future<Account> loginWithExternalSignerAndCallbacks({
  required String pubkey,
  required FutureOr<String> Function(String) signEvent,
  required FutureOr<String> Function(String, String) nip04Encrypt,
  required FutureOr<String> Function(String, String) nip04Decrypt,
  required FutureOr<String> Function(String, String) nip44Encrypt,
  required FutureOr<String> Function(String, String) nip44Decrypt,
}) => RustLib.instance.api.crateApiSignerLoginWithExternalSignerAndCallbacks(
  pubkey: pubkey,
  signEvent: signEvent,
  nip04Encrypt: nip04Encrypt,
  nip04Decrypt: nip04Decrypt,
  nip44Encrypt: nip44Encrypt,
  nip44Decrypt: nip44Decrypt,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartSigner>>
abstract class DartSigner implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Creates a new DartSigner with the given callbacks.
  static Future<DartSigner> newInstance({
    required PublicKey pubkey,
    required FutureOr<String> Function(String) signEvent,
    required FutureOr<String> Function(String, String) nip04Encrypt,
    required FutureOr<String> Function(String, String) nip04Decrypt,
    required FutureOr<String> Function(String, String) nip44Encrypt,
    required FutureOr<String> Function(String, String) nip44Decrypt,
  }) => RustLib.instance.api.crateApiSignerDartSignerNew(
    pubkey: pubkey,
    signEvent: signEvent,
    nip04Encrypt: nip04Encrypt,
    nip04Decrypt: nip04Decrypt,
    nip44Encrypt: nip44Encrypt,
    nip44Decrypt: nip44Decrypt,
  );
}
